import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Orange Paithani Silk Dupatta",
    description: "Handwoven Silk Paithani Dupatta with Zari Bootis",
    price: "5000",
    discountedPrice: "3600",
    categoryName: "Dupatta",
    imageLink: "/images/dupatta/dupatta1.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 3.5,
    size: "2.5 meters",
    inStock: true,
    deliveryTime: "6",
    reviews: "3.1k"
  },
  {
    _id: uuid(),
    title: "Bottle Green Paithani Silk Saree",
    description: "Zari Woven Traditional Paithani Silk",
    price: "18900",
    discountedPrice: "9300",    
    categoryName: "Saree",
    imageLink: "/images/saree/saree3.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 4.1,
    size: "5.5 meters",
    inStock: true,
    deliveryTime: "4",
    reviews: "1k"
  },
  {
    _id: uuid(),
    title: "Green Paithani Silk Salwar suit",
    description: "Paithani Silk Hand Woven Salwar Suit",
    price: "8500",
    discountedPrice: "4200",
    categoryName: "Kurti",
    imageLink: "/images/kurti/kurti2.jpg",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 3,
    size: "M",
    inStock: true,
    deliveryTime: "7",
    reviews: "2.3k"
  },
  {
    _id: uuid(),
    title: "Peach Paithani Silk Lehenga",
    description: "Paithani Silk Un-stitched lehenga embroidered with floral & cultural motif embellishments",
    price: "38500",
    discountedPrice: "20130",
    categoryName: "Lehenga",
    imageLink: "/images/lehenga/lehenga4.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 4.4,
    size: "Onesize",
    inStock: true,
    deliveryTime: "5",
    reviews: "1.6k"
  },
  {
    _id: uuid(),
    title: "Pista Green Paithani Silk Dupatta",
    description: "Handwoven Silk Paithani Dupatta with Zari Stripes",
    price: "16000",
    discountedPrice: "14080",
    categoryName: "Dupatta",
    imageLink: "/images/dupatta/dupatta5.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 1.8,
    size: "3 meters",
    inStock: true,
    deliveryTime: "3",
    reviews: "970"
  },
  {
    _id: uuid(),
    title: "Red Paithani Silk Saree",
    description: "Zari Woven Traditional Paithani Silk",
    price: "19900",
    discountedPrice: "10350",    
    categoryName: "Saree",
    imageLink: "/images/saree/saree2.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 3.1,
    size: "6 meters",
    inStock: true,
    deliveryTime: "8",
    reviews: "4k" 
  },
  {
    _id: uuid(),
    title: "Violet Paithani Silk Dupatta",
    description: "Handwoven Silk Paithani Dupatta with Zari Bootis",
    price: "4500",
    discountedPrice: "2650",
    categoryName: "Dupatta",
    imageLink: "/images/dupatta/dupatta4.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 2.9,
    size: "3.5 meters",
    inStock: true,
    deliveryTime: "5",
    reviews: "1.4k"
  }, 
  {
    _id: uuid(),
    title: "Cream Paithani Lehenga",
    description: "Paithani Silk Un-stitched lehenga embroidered with regal flair",
    price: "36000",
    discountedPrice: "23500",
    categoryName: "Lehenga",
    imageLink: "/images/lehenga/lehenga1.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 2.9,
    size: "Onesize",
    inStock: true,
    deliveryTime: "7",
    reviews: "800" 
  },
  {
    _id: uuid(),
    title: "Magenta Paithani Silk Dupatta",
    description: "Handwoven Silk Paithani Dupatta with Zari Bootis",
    price: "4000",
    discountedPrice: "2170",
    categoryName: "Dupatta",
    imageLink: "/images/dupatta/dupatta3.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 4.7,
    size: "2.5 meters",
    inStock: true,
    deliveryTime: "6",
    reviews: "2k"
  },
  {
    _id: uuid(),
    title: "Pista Green Paithani Silk Lehenga",
    description: "Paithani Silk Un-stitched lehenga embroidered cultural motif embellishments",
    price: "33300",
    discountedPrice: "18590",
    categoryName: "Lehenga",
    imageLink: "/images/lehenga/lehenga2.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 5,
    size: "Onesize",
    inStock: true,
    deliveryTime: "4",
    reviews: "690" 
  },
  {
    _id: uuid(),
    title: "Rani Pink Paithani Silk Salwar suit",
    description: "Beautiful suit Jacquard Paithani Salwar suit with Zari Work",
    price: "2500",
    discountedPrice: "2300",    
    categoryName: "Kurti",
    imageLink: "/images/kurti/kurti1.jpg",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 4.5,
    size: "S",
    inStock: true,
    deliveryTime: "8",
    reviews: "4k"
  },
  {
    _id: uuid(),
    title: "Light Pink Paithani Silk Salwar suit",
    description: "Paithani and Zari Work Un-stitched Salwar suit dress",
    price: "6800",
    discountedPrice: "4100",
    categoryName: "Kurti",
    imageLink: "/images/kurti/kurti5.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 4,
    size: "XL",
    inStock: true,
    deliveryTime: "7",
    reviews: "3.7k"
  },
  {
    _id: uuid(),
    title: "Cyan Blue Paithani Upada Silk Lehenga",
    description: "Paithani Silk Un-stitched lehenga embroidered with cultural motif embellishments",
    price: "30900",
    discountedPrice: "19900",
    categoryName: "Lehenga",
    imageLink: "/images/lehenga/lehenga5.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 3.3,
    size: "Onesize",
    inStock: true,
    deliveryTime: "6",
    reviews: "2.5k"
  },
  {
    _id: uuid(),
    title: "Red Paithani Silk Lehenga",
    description: "Paithani Silk Un-stitched lehenga embroidered with floral embellishments",
    price: "35600",
    discountedPrice: "21500",
    categoryName: "Lehenga",
    imageLink: "/images/lehenga/lehenga6.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 2.8,
    size: "Onesize",
    inStock: true,
    deliveryTime: "9",
    reviews: "1.7k" 
  },
  {
    _id: uuid(),
    title: "Turquoise Green Paithani Silk Saree",
    description: "Zari Woven Traditional Paithani Silk",
    price: "17000",
    discountedPrice: "10000",    
    categoryName: "Saree",
    imageLink: "/images/saree/saree1.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 4.9,
    size: "6.5 meters",
    inStock: true,
    deliveryTime: "4",
    reviews: "730"
  },
  {
    _id: uuid(),
    title: "Dark Green Paithani Silk Salwar suit",
    description: "Jacquard Paithani and Zari Work Un-stitched Salwar suit dress",
    price: "5820",
    discountedPrice: "2000",    
    categoryName: "Kurti",
    imageLink: "/images/kurti/kurti3.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 1.3,
    size: "L",
    inStock: true,
    deliveryTime: "5",
    reviews: "4.3k"
  },
  {
    _id: uuid(),
    title: "Black Paithani Silk Saree",
    description: "Zari Woven Traditional Paithani Silk",
    price: "20800",
    discountedPrice: "9700",    
    categoryName: "Saree",
    imageLink: "/images/saree/saree4.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 4.7,
    size: "6 meters",
    inStock: true,
    deliveryTime: "7",
    reviews: "3.8k" 
  },
  {
    _id: uuid(),
    title: "Rani Pink Paithani Silk Dupatta",
    description: "Handwoven Silk Paithani Dupatta with Zari Bootis",
    price: "13000",
    discountedPrice: "6500",
    categoryName: "Dupatta",
    imageLink: "/images/dupatta/dupatta2.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 5,
    size: "2.5 meters",
    inStock: true,
    deliveryTime: "6",
    reviews: "3.4k" 
  },
  {
    _id: uuid(),
    title: "Magenta Katan Silk Paithani Saree",
    description: "Magenta paithani saree in pure katan silk banarasi handloom base",
    price: "9000",
    discountedPrice: "4670",    
    categoryName: "Saree",
    imageLink: "/images/saree/saree5.webp",
    carted: false,
    wished: false,
    qty: 0, 
    rating: 3.4,
    size: "5.5 meters",
    inStock: true,
    deliveryTime: "7",
    reviews: "2.6k" 
  },
];